### ISSUE TITLE
Additions for macOS

### ISSUE THREAD

**Issue by jspencer** [branan/teensy#1]
Thanks for writing this guide!

I was able to get everything running on macOS with only a few minor changes.

To install the linker et. al., I used the [homebrew](http://brew.sh) package manager.
`brew cask install gcc-arm-embedded`

Also my teensy loader was `teensy_loader_cli` rather than `teensy-loader-cli` so I had to change that. Looking at the [documents over at pjrc](https://www.pjrc.com/teensy/loader_cli.html) I see that the documentation for Linux uses underscores as well, so  Linux users on other distros may run into the same issue I did.

Now on to figuring out interrupts... I'm looking forward to your next post.

**Comment by branan** [comment]
I'm happy to add a note to post 1 about the correct GCC for embedded ARM on mac. Thanks for the info there! And looking at my distro packages, it appears that they rename the binary. I'll update the post to use the correct form for most platforms (the code in this repo will stay with dashes, since that's what works for me).

As for interrupts... I think they'll be in Post 3, which is going to be mostly looking at error handling. That will include not just handling panics, but also catching hardware faults.
