### ISSUE TITLE
Clippy seems unstable

### ISSUE THREAD

**Issue by paulirotta** [branan/teensy#3]
I'm seeing problems with clippy at the moment, will disable it locally and continue. Let me know if there is a workaround.

error[E0004]: non-exhaustive patterns: `Catch(_)` not covered
  --> C:\Users\pauli\.cargo\registry\src\github.com-1ecc6299db9ec823\clippy_lints-0.0.119\src\utils\sugg.rs:90:15
   |
90 |         match expr.node {
   |               ^^^^^^^^^ pattern `Catch(_)` not covered

**Comment by branan** [comment]
Clippy is definitely unstable, unfortunately. It relies on the guts of the compiler, and will sometimes break with the latest nightly. I have it enabled on this repo for my own benefit when working on the blog, but I explicitly left it out of my instructions in the text for precisely this reason.

I'd welcome patches to make it optional. Unfortunately I've barely had enough time to work on the tutorial part of this (it's been over a month since the last blog post!) and I doubt I'll get around to fixing it up myself any time soon.

**Comment by branan** [comment]
Update, over a year later: I'm working on a V2 of this, and now that clippy is in rustup I'll be able to remove it from the cargo.lock.

**Comment by branan** [comment]
I've pushed up versions of the code that no longer use clippy as a plugin (plus some other updates for modern nightly compilers!).
